mawaqit_url: https://mawaqit.net/fr/mosquee-ennour-sartrouville
adhan_url: http://91.167.152.138:32481/share/Xm9QULyw4FTl5lL_/adhan%20makkah.mp3
#https://download.tvquran.com/download/TvQuran.com__Athan/TvQuran.com__05.athan.mp3
fajr_adhan_url: http://91.167.152.138:32481/share/4zH8WRT2525hhJ4j/Adhan_Fajr_Mishary%20Rashid%20Alafasy.mp3
google_home_name: 'Google Home mini'
volumes:
  - prayer_name: Fajr
    volume: 5
  - prayer_name: Dhuhr
    volume: 25
  - prayer_name: Asr
    volume: 25
  - prayer_name: Maghrib
    volume: 25
  - prayer_name: Isha
    volume: 25